### PR TITLE
added missing lifecycle method 'componentDidUnload'

### PR DESCRIPTION
**Pull request by sledsworth**
Fix for issue #5

### CODE REVIEW

**Comment by sledsworth** [comment]
> Awesome!
> I also noticed that `componentDidUpdate` is missing too, in case you also want to fix that.

@ncardeli It looks like it is already in there? https://github.com/ionic-team/stencil-eslint/blob/cc8b58c989f23b2c4384130894fd5fc1efa56ad7/src/utils.ts#L81

**Comment by ncardeli** [comment]
Sorry, you're right.
Thanks for the fix 👍

**Comment by sledsworth** [comment]
Are the maintainers of this repo active anymore? I'd like to get this merged.

**Comment by gdfreitas** [comment]
> Are the maintainers of this repo active anymore? I'd like to get this merged.

Me too

**Comment by jevenson** [comment]
@manucorporat would you able to take a look at the work that @sledsworth did? This would be a great addition to the eslint plugin, if accepted

**Comment by valadas** [comment]
I ran into this, just commenting to be notified when it get's merged

**Comment by jevenson** [comment]
@valadas in the future, you can click the Subscribe button on the right to get notifications for a Pull Request or Issue without having to leave a comment

**Comment by sledsworth** [comment]
@manucorporat mentioned on the stencil slack that he'd look into merging this comically small outstanding PR this weekend. 😆

**Comment by sledsworth** [comment]
After chatting with @manucorporat, it is suggested that `disconnectedCallback` is used instead of `componentDidUnload`, which will be deprecated in the future.

https://stenciljs.com/docs/component-lifecycle#disconnectedcallback

**Pull request closed without merging**
